# Generated by Django 4.2.10 on 2024-02-22 12:46

from django.db import migrations, models
import uuid




class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customuser_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
