# Generated by Django 4.2.10 on 2024-02-22 12:55

from django.db import migrations
import uuid

def generate_slug(apps, schema_editor):
    CustomUser = apps.get_model("main", "CustomUser")
    users = CustomUser.objects.all()

    for user in users:
        user.slug = uuid.uuid4()
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customuser_slug'),
    ]

    operations = [
        migrations.RunPython(generate_slug),
    ]
