# Generated by Django 4.2.10 on 2024-02-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='response_type',
            field=models.CharField(blank=True, choices=[('Yes/No', 'Yes/No'), ('Words Only', 'Words Only'), ('Multiple Choice', 'Multiple Choice')], default=None, max_length=150, null=True),
        ),
    ]
