# Generated by Django 4.2.10 on 2024-02-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_answer_body_answer_multiple_choice_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='multiple_choice_number_of_options',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
