# Generated by Django 4.2.10 on 2024-02-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_question_multiple_choice_number_of_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='confirmed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
