# Generated by Django 4.2.10 on 2024-03-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_question_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='allow_explanation',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
